baseURL = "http://example.org/"
languageCode = "da"
title = "My New Hugo Site"
theme = "systematik"
sectionPagesMenu = "main"

[[menu.main]]
    name = "Hjem"
    title = "Hjem"
    weight = 1
    identifier = "Hjem"
    url = "/"

    # [[menu.main]]
    # name = "Kontakt"
    # title = "Kontakt"
    # weight = 2
    # identifier = "Kontakt"
    # url = "/Kontakt/"

    [[menu.main]]
    name = "Post"
    title = "Post"
    weight = 3
    identifier = "post"
    url = "/post/"
    # 
    # [[menu.main]]
    # name = "Datavisualisering"
    # title = "Datavisualisering"
    # weight = 4
    # identifier = "Datavisualisering"
    # url = "/datavisualisering/"
