baseURL = "http://example.org/"
languageCode = "da"
title = "My New Hugo Site"
theme = "systematik"
sectionPagesMenu = "main"

[[menu.main]]
    name = "Hjem"
    title = "Hjem"
    weight = 1
    identifier = "Hjem"
    url = "/"

    [[menu.main]]
    name = "Kontakt"
    title = "Kontakt"
    weight = 3
    identifier = "Kontakt"
    url = "/Kontakt/"

    [[menu.main]]
    name = "Post"
    title = "Post"
    weight = 4
    identifier = "post"
    url = "/post/"
